language: bash

matrix:
  include:
    - os: linux
      env: FUGUE_RELEASE="2017.05.23" FUGUE_VERSION="0.30.9-1964"
    - os: linux
      env: FUGUE_RELEASE="2017.06.12" FUGUE_VERSION="0.34.11-2156"

env:
  global:
    - secure: "hvz3pCdQprlzOw4WS7FzOLTeeOFot+lA4FUYdX8x0ac93lGOS3tnYphrdchEe07a/YeysVit1OuMQo7aXqIVUJpc+E04cPWiD8gEX6nJZhHg/WMFNbvzHBIbkIRapsiBZyMNtGRRa+Tsa5S8DS5YPzHyaNoeIE9OR26BH80s72bhHY23aTdmlSrB2pm8MJNO8cGDddAKsZ6srpdpehmtxFbnvpd2Oo0cygyH26DoOuFX+SSuPeBf/0r50IWLcfcBQOt20vQTcrgM7bXW3fY9F6gKex85vZtm0fmSmNlQTqI//tSE2OiCkeqNOHysEOI+mIEHjz2BItyXJWHHkYxmY/Mm9tVmcU0nShhsxUznS4gmv5zQ8ig33R2mvIYSEkoqSoHnLSU4/I5kHbJ7fwrmiIBvIDeKVMNeSa5wShNrffH5Ps9Y2MLDisi6kQDmT1TUBNIzpocVCcaLXh1/mfboF6cs64Wkw05K+mjHOK7wkCxVy8Wv4pgpqbgzVnXG36XOU47dsu0rHoIXaS0Xl+G2vMTraPJIt3qf34FdmXpT8DIJK6Zt7Ja7ZgaXurzkvf4luv6RnXC+nnIVn+SiH0n5b394q5wLEAWbkKksagMo+YkxCQqC4RPIGyN17QqbQhoeAUYkxydkk/qODc43dwatloe58OlfYlzfb1az2S+NG6k="
    - secure: "C5r0+oeLoYTM0JIZGkdrXKyzPa9M15tgWw3FbII1UKAZZ7laB5uysaow6EykNgwCDhLTmL5SL3FZoe0Y04XOzA3N4vTQJ2I7/hnsk68uh1mbOqZblcjzQ75lvPuA7t2nqQT22oBOARjw+CuLqs5zvJqx2PuBwAkDLxMTsVHKtx4qWf1xn4bkNACuqjircybBa86iXP3RxI6W113Lgp5HQpJD5cY8EEizv4gjeMDLNmlAibDrWHf2+WA0MELZF3kmA0qQtsQqVosT8gC2ZqYtPyXPkAgy9gSWOU7FbZI/RQUX4/Hha/NB2MCykvNGBGXGs9ybNaffjY1CodvfKhuv5Uvo/piuKg6aCE384A41YRqkNcXMnvbQIc+nGrWPGGtssHDlZW7X8jZRn3Y2vnWvbdlPSDJERdRWxd3M3vWmUJZfcJo+NC5+vMPFsNBxdeKm919YOu+BBQ/DdK5FBy5ocWtq8Hxg5Pc3XPMvfo8PCeUUVyZjmADKrZKRf95hakYhW3gn6YaxuZ45TYsJkIVEao1K6ZY0dd03x9VvJYqW5J8MXzC8mD10D4OSOMmgEofmNQLI7ly440gVxDzZmeLM5ZAwodPqLFWevHLR9zG9mU6xnO00eQPZibFQ99900o+RZKTip+SvFn1CcKk++ygHT6AJ1lEpfV65GF5b2mv0H0A="

before_install:
  - sudo pip install awscli
  - aws s3 cp s3://saboRepo/${FUGUE_RELEASE}/fugue-client_${FUGUE_VERSION}_amd64.deb fugue-cli.deb

install:
  - sudo dpkg --install fugue-cli.deb  

script:
  make 
